### ISSUE TITLE
step-by-step branch missing referenced in video

### ISSUE THREAD

**Issue by kinakuta** [g0t4/pluralsight-modern-async-js#1]
There step-by-step branch is referenced in the Pluralsight video which has `multiDone.js` and `multiDone.tests.js` but it doesn't appear to be present on the publicly viewable repository.

**Comment by g0t4** [comment]
I might've accidentally deleted it, let me check

**Comment by g0t4** [comment]
FYI the course demo files have the entire repo of all changes made during the course.

**Comment by kinakuta** [comment]
I actually found the missing files in someone else's fork of this repo (I'm guessing they pulled them from the demo files for the course), but I thought I'd let you know anyway. Thanks.

**Comment by g0t4** [comment]
Fixed! Thanks for pointing this out @kinakuta
